### ISSUE TITLE
0.2.5 doesn't work with Ruby 2.0

### ISSUE THREAD

**Issue by anthonyryan1** [gemnasium/gemnasium-gitlab-service#1]
The Travis-CI build failed for the 2.0 build and tests.

Is 0.2.4 intended to be the last release supporting ruby 2.0 or was this an oversight?

**Comment by halfbyte** [comment]
Please note that this breaks all Gitlab installs running on Ruby 2.0 that are currently trying to update to GL 7.9 which has 0.2.5 of this gem as a dependency. 

The offender is a required keyword argument in Line 17 of [lib/gemnasium/gitlab_service/client.rb](https://github.com/gemnasium/gemnasium-gitlab-service/blob/master/lib/gemnasium/gitlab_service/client.rb#L17)

I don't really see any need to use keyword arguments here. I've made the botched Gitlab 7.9 update work by just converting them to non-kw arguments, but as I don't use the Gemnasium integration in Gitlab, I can't really say if it would break things. I'll try to submit a PR.

**Comment by anthonyryan1** [comment]
Closing per #2 and the recent release.
